import dotenv from "dotenv";
import { EventEmitter } from "events";

dotenv.config();
global.cmds = {};
global.user = {};
global.presences = {};
global.functions = {};
global.games = {};
global.intervals = {};
global.anonymous = new Map();
global.cache = {};
cache.metadata = new Map();
global.packname = "Made by Void";
global.author = "Powered by Hidden Finder";
intervals.tebakGambar = new Map();
intervals.sudoku = new Map();
intervals.url = new Map();
intervals.anonymous = new Map();
intervals.word = new Map();
games.tebakGambar = new Map();
games.sudoku = new Map();
games.akinator = new Map();
games.tictactoe = new Map();
games.word = new Map();
games.werewolf = new Map();
user.cooldown = new Map();
cmds.commands = new Map();
user.afk = new Map();
global.commandsPath = [];
cmds.aliases = [];
global.log = console.log;
EventEmitter.prototype.setMaxListeners(0);

await import("./connect.js");
